# Generated by Django 3.0.6 on 2021-08-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210820_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='messsage',
        ),
    ]
