# Generated by Django 3.0.6 on 2021-08-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210820_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='messsage',
            new_name='message',
        ),
    ]
