# Generated by Django 3.2.4 on 2021-08-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
